### ISSUE TITLE
Does this work?

### ISSUE THREAD

**Issue by natewalck** [J-Nistler/Nomad3-Klipper#1]
Hey J!  I was curious if you got this working well on Klipper or if it was in very early stages. I'm looking for something to replace Carbide Motion (and ideally run on a RPi) and came across this.

**Comment by J-Nistler** [comment]
Hey Nate! Yes, I got Klipper and Mainsail to work well for my Ender 3 Pro with this printer configuration file. That said, it's very customized to my setup (e3dv6 hot end, skr mini e3 main board, different printing volume from stock, custom tuning config, etc.). You're welcome to use it, but know that the best avenue for getting Klipper set up is to build your own config file from scratch entirely spec'd for your machine. I found that using other configs as a reference was super helpful, though, so go for it!

**Comment by J-Nistler** [comment]
No further action required; reach out if you have any further questions!
